site_name: Docs

repo_url: https://github.com/elderlydoofus/docs
repo_name: elderlydoofus/docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - toc:
        permalink: "#"
